module.exports = [
  {
    id: 1,
    name: "Enterprise employee tracker",
    coverURL: "http://source.unsplash.com/wpU4veNGnHg/5472x3648",
    background: "#e9d8a6",
    container: "#ee9b00",
    cover: "#ae2012",
    buttonColor: "before:bg-rose-600 hover:border-green-800",
    description:
      "With defined work zones, you can track employee locations and get a final performance index based on their past time within that zone.",
    githubURL:
      "https://github.com/Jesusm1229/MonitorSystem_React/tree/master/src",
    previewURL: "https://fifth-being-338704.web.app/",
    tools: ["ASP.NET CORE", "ReactJs", "SQL SERVER", "Google API"],
    pinned: false,
  },
  {
    id: 2,
    name: "ShareMe - Social Network ",
    coverURL: "http://source.unsplash.com/SYTO3xs06fU/6000x4000",
    background: "#001d3d",
    container: "#669bbc",
    cover: "#01497c",
    buttonColor: "before:bg-fuchsia-800 hover:border-green-800",
    description:
      "This project offers an intuitive web page where users can share their photographic content to the world.",
    githubURL: "https://github.com/Jesusm1229/shareme_frontend",
    previewURL: "https://sharemejm.netlify.app/",
    tools: ["React", "Sanity"],
    pinned: false,
  },
  {
    id: 3,
    name: "IP address tracker",
    coverURL: "https://imgur.com/4dZRefD.png",
    background: "#a7a6a6",
    description:
      "it tracks many things by your IP address such as Location, Network, Area, Coordinate, etc",
    githubURL: "https://github.com/j471n/ip-address-tracker",
    previewURL: "",
    tools: ["HTML", "CSS", "JS"],
    pinned: false,
  },
  {
    id: 4,
    name: "IP address tracker",
    coverURL: "https://imgur.com/4dZRefD.png",
    background: "#fa0",
    description:
      "it tracks many things by your IP address such as Location, Network, Area, Coordinate, etc",
    githubURL: "https://github.com/j471n/ip-address-tracker",
    previewURL: "",
    tools: ["HTML", "CSS", "JS"],
    pinned: false,
  },
  {
    id: 5,
    name: "ghost invasion game",
    coverURL: "https://imgur.com/fVbFbqw.png",
    background: "#85df5e",
    description:
      "This the fun game build using PyGame library, in this there are ghost and you just have to kill them by just shooting.",
    githubURL: "https://github.com/j471n/ghost-invasion-game-python",
    previewURL: "",
    tools: ["python", "PyGame"],
    pinned: false,
  },
  {
    id: 6,
    name: "ghost invasion game",
    coverURL: "https://imgur.com/fVbFbqw.png",
    background: "#0af",
    description:
      "This the fun game build using PyGame library, in this there are ghost and you just have to kill them by just shooting.",
    githubURL: "https://github.com/j471n/ghost-invasion-game-python",
    previewURL: "",
    tools: ["python", "PyGame"],
    pinned: false,
  },
];
