module.exports = [
  {
    id: 1,
    name: "Enterprise employee tracker",
    coverURL: "http://source.unsplash.com/IFM29XVI2EI/2400x1600",
    background: "#053c5e",
    container: "#fff8f0",
    cover: "#a31621",
    buttonColor: "before:bg-rose-600 hover:border-green-800",
    description:
      "With defined work zones, you can track employee locations and get a monthly, weeekly and daily performance index based on their past time within that zone.",
    githubURL:
      "https://github.com/Jesusm1229/MonitorSystem_React/tree/master/src",
    previewURL: "https://fifth-being-338704.web.app/",
    tools: ["ASP.NET CORE", "ReactJs", "SQL SERVER", "Google API"],
    pinned: false,
  },
  {
    id: 2,
    name: "ShareMe - Social Network ",
    coverURL: "http://source.unsplash.com/SYTO3xs06fU/2400x1600",
    background: "#06bcc1",
    container: "#669bbc",
    cover: "#01497c",
    buttonColor: "before:bg-fuchsia-800 hover:border-green-800",
    description:
      "This project offers an intuitive web page where users can share their photographic content with the world.",
    githubURL: "https://github.com/Jesusm1229/shareme_frontend",
    previewURL: "https://sharemejm.netlify.app/",
    tools: ["React", "Sanity"],
    pinned: false,
  },
  {
    id: 3,
    name: "PWA WeatherApp",
    coverURL: "http://source.unsplash.com/ugnrXk1129g/2400x1594",
    background: "#3c6e71",
    container: "#f7fff7",
    cover: "#353535",
    description: "This app lets you know the weather condition of any city.",
    githubURL: "https://github.com/Jesusm1229/weather-app",
    previewURL: "https://weather-app-b5ad2.web.app/",
    tools: ["Angular", "OpenWeather API", "Typescript", "Service Worker"],
    pinned: false,
  },
  {
    id: 4,
    name: "Twitter hate speech tracker",
    coverURL: "http://source.unsplash.com/5otlbgWJlLs/2400x1600",
    background: "#ef476f",
    container: "#ffccd5",
    cover: "#540d6e",
    description:
      "Using the Twitter API, this project scraps those tweets considered hate speech and returns an indexed percentage filtered by their common origin.",
    githubURL: "https://github.com/Jesusm1229/HateSpeech_Tracker",
    previewURL: "https://github.com/Jesusm1229/HateDashboard",
    tools: ["Python", "Hadoop", "Java"],
    pinned: false,
  },
  {
    id: 5,
    name: "Ecommerce 'El Vecino Tarazona'",
    coverURL: "http://source.unsplash.com/D4ZtZX1UeAI/2400x1820",
    background: "#2ec4b6",
    container: "#eacdc2",
    cover: "#ffa69e",
    description:
      "E-commerce for a grocery store. The user can have a favorite list and receive notifications when a product is renewed. The page includes a PayPal payment gateway.",
    githubURL: "https://github.com/Jesusm1229/tiendafrontend",
    previewURL: "https://tienda-database-a1d33.firebaseapp.com/ ",
    tools: ["React", "Google Firebase", "Paypal API"],
    pinned: false,
  },
  {
    id: 6,
    name: "Employment platform",
    coverURL: "http://source.unsplash.com/rxpThOwuVgE/2400x1349",
    background: "#252422",
    container: "#ccc5b9",
    cover: "#eb5e28",
    description:
      "A closed platform where IT recruiters can make job postulations in diverse areas (FrontEnd, Backend, DevOps, Q&A, Database) with a single-selection test attached to it; those job seekers who give the best answer will have a higher position in the dedicated ranking.",
    githubURL: "https://github.com/Jesusm1229/abc",
    previewURL: "https://github.com/Jesusm1229/abc",
    tools: ["Java"],
    pinned: false,
  },
];
